apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: "*"
    helm:
      values: |
        replicaCount: 1

        httpsEnabled: false
        containerPorts:
          http: 8080
        service:
          type: NodePort
          ports:
            http: 80
          nodePorts:
            http: 30081

        existingServerBlockConfigmap: my-nginx-serverblock

        staticSite:
          enabled: true
          content: |
            <!DOCTYPE html>
            <html>
            <body>
              <h1>ArgoCD + Helm Demo</h1>
              <p>Status: <b>v1</b></p>
            </body>
            </html>

        networkPolicy:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # 🔄 Auto-sync enabled
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
